---
- name: Install dnsmasq
  become: true
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Configure dnsmasq
  become: true
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/custom.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dnsmasq
